version: '3.7'
networks:
  default:
    external:
      name: infra
services:
  jenkins-master:
    image: "qaprosoft/jenkins-master:${TAG_JENKINS_MASTER}"
    container_name: jenkins-master
    environment:
      - "INFRA_HOST=${INFRA_HOST}"
      - "ROOT_URL=${ROOT_URL}"
      - "SONAR_URL=${SONAR_URL}"
      - "ADMIN_USER=${JENKINS_ADMIN_USER}"
      - "ADMIN_PASS=${JENKINS_ADMIN_PASS}"
      - "ROOT_EMAIL=${JENKINS_ROOT_EMAIL}"
      - "ADMIN_EMAILS=${JENKINS_ADMIN_EMAILS}"
    volumes:
     # TODO: test plugins https://github.com/qaprosoft/jenkins-master/issues/193
     # to add extra plugins follow this steps: https://github.com/qaprosoft/jenkins-master/releases/tag/4.6
     - "data-volume:/var/jenkins_home:rw"
    ports:
     - "50000:50000"
    restart: always
  jenkins-slave:
    image: "qaprosoft/jenkins-slave:${TAG_JENKINS_SLAVE}"
    container_name: jenkins-slave
    environment:
     - "JENKINS_MASTER_URL=http://jenkins-master:8080/jenkins"
     - "JENKINS_MASTER_USERNAME=${JENKINS_ADMIN_USER}"
     - "JENKINS_MASTER_PASSWORD=${JENKINS_ADMIN_PASS}"
     - "JENKINS_SLAVE_NAME=jenkins-slave"
     - "JENKINS_SLAVE_WORKERS=5"
     - "JENKINS_SLAVE_LABELS=default maven api web docker"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
     - "8001:8000"
    depends_on:
     - "jenkins-master"
    restart: always
volumes:
  data-volume:

